### ISSUE TITLE
Realtime not working

### ISSUE THREAD

**Issue by imbhavin95** [ammezie/laravel-chat#2]
After message send destination side have to refresh tab not auto load chat like proper chat functionality. how to set auto refresh chat body.

**Comment by ammezie** [comment]
I don't understand what you mean.

**Comment by imbhavin95** [comment]
it means Real time chatting is not working. it means if user1 send message to user2 so user2 have to refresh page to view message of user1.

**Comment by ammezie** [comment]
It is working as expected (with real-time chatting) over here. Probably something is wrong from your side.

**Comment by imbhavin95** [comment]
Which thing you expect is wrong?

**Comment by ammezie** [comment]
Probably your Pusher credentials. Open dev tools to see if there are any kind of errors.

**Comment by devvrat-sharma** [comment]
Real time chatting not working.
To see the mesages i have to refresh the page everytime.

**Comment by NicholasDShaw** [comment]
This happened to me too, it was because the pusher cluster was staticly set to 'eu' in public/js/app.js

You will get errors in the javascript console when the cluster isn't set to the correct value.

After changing that to the correct cluster it works. 

@ammezie I recommend creating an environment variable in .env.example for the cluster to have that set dynamically in public/js/app.js and config/broadcasting.php

**Comment by ammezie** [comment]
Thanks for pointing that out. As at the time of creating the app, Pusher cluster is not required to be explicitly set. I will update the code and readme as well.

**Comment by ammezie** [comment]
I have updated the code and the readme, hence I'm closing this.

**Comment by Legend23** [comment]
I have to refresh the page to see the difference. So i went to the console log and see this. 

I don't understand the problem. 

![pusher](https://user-images.githubusercontent.com/3600281/47668643-4518a880-dba9-11e8-8bdf-e77e93ba68b0.PNG)
